# Generated by Django 3.0 on 2021-06-17 13:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[], max_length=6)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.About')),
            ],
        ),
    ]
