# Generated by Django 3.0 on 2021-06-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVariationLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('sizeVariation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.SizeVariation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=6)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('available_colours', models.ManyToManyField(blank=True, to='cart.ColourVariation')),
                ('available_sizes', models.ManyToManyField(to='cart.SizeVariation')),
                ('primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_productlangs', to='cart.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
                ('secondary_categories', models.ManyToManyField(blank=True, to='cart.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ColourVariationLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('colourVariation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.ColourVariation')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylangs', to='cart.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
