# Generated by Django 3.2 on 2021-09-11 17:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210810_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_detail',
            new_name='ProductDetail',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='this is place for the title of the product', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(help_text='this is place for the title of the product', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_fr',
            field=models.CharField(help_text='this is place for the title of the product', max_length=150, null=True),
        ),
    ]
