# Generated by Django 3.2 on 2021-09-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210911_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
