# Generated by Django 3.2 on 2022-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220718_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.ImageField(upload_to='Featured_images/%Y/%m/%d'),
        ),
    ]
