# Generated by Django 3.0.6 on 2021-04-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210413_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
    ]
